{% set name = "python-barcode" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b1825fbdb11e597466dff4286b4ea9b1e86a57717b59e563ae679726fc854de

build:
  skip: True                    # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - python-barcode = barcode.pybarcode:main


requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - wheel
  run:
    - python

test:
  requires:
    - pip
    - pytest
    - pillow
  commands:
    - pip check
    - python-barcode --help
    - pytest
  imports:
    - barcode
  source_files:
    - tests

about:
  home: https://github.com/WhyNotHugo/python-barcode
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: python-barcode provides a simple way to create barcodes in Python.
  dev_url: https://github.com/WhyNotHugo/python-barcode
  doc_url: https://python-barcode.readthedocs.io/en/stable/
  description: python-barcode provides a simple way to create barcodes in Python.


extra:
  recipe-maintainers:
    - sodre
