travis:
  secure:
    BINSTAR_TOKEN: G9bOdR7hfBhEJEHuQVV+haE03qcHyRR13tub8g5rxVqMHbWgr+JUPEMADitqokcHAA364YizcvU7iLTQWpMKfLqpO57YkdwN39clE2q617efMDu8pE3bZpGM7kTSn0dtP86/pEdduZvfrct3p0kB4liALICAeJA6obFSTD9cG8rxQfqtjO/Vte3dQPAIxvfPHZ62TP7jeEObvpwGqUyH1An7xoWA16PBjnMO8/PRdfgeYg5nsf1VuDGgTfb/kCwv3h5+4iGLfHyIZdeBsWXAa5uk19SIOCbt1no12FoOVSmtHPltSZyIH+vbfxQKKwsBt1l6PUsD96Gx8XY0NJYUYvFENiXkElBoJMaNF56mT0lHmBEubuAHR8b+3NJGy7WV6SQcW/knloLCGbNXfR9GphUd0xgPZTB0XYJlDO0ortH/yQkjBJDsDU+iubFsykETVL/5KIh9MT4S1RsTHoodBCjGif726Bt3ivIml3bjeql8iX83tnfFnomw7yqmIAtvgGrSRUnfU+E4p67D2Kb+DNYb6QmkirMJTtjAfc8hGbCi9Mhzn+IHkFGQG+oWtMHXHXgpYHMtRWL1g15Rk/y3gq5r4q3jZ2q5FZGWEp4N1VxgN3tKqehkGILCRMqblong2dZR4rZ6jZoz/0XXYYORd5Dl4tl1HNvHBqxN1qd0ScM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
